# Generated by Django 5.1.7 on 2025-03-27 16:30

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_populate_share_tokens'),
    ]

    operations = [
        migrations.AlterField(
            model_name='desk',
            name='share_token',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
