# Generated by Django 5.1.7 on 2025-03-27 18:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0003_alter_desk_share_token'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DeskGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('group_type', models.CharField(choices=[('view', 'View Only'), ('admin', 'Admin'), ('owner', 'Owner')], max_length=10)),
                ('is_default', models.BooleanField(default=False)),
                ('desk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='todo.desk')),
            ],
            options={
                'unique_together': {('desk', 'name')},
            },
        ),
        migrations.CreateModel(
            name='DeskUserShare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('desk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_shares', to='todo.desk')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='todo.deskgroup')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='desk_shares', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('desk', 'user')},
            },
        ),
    ]
