# Generated by Django 5.1.7 on 2025-03-25 14:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0004_remove_workplace_manager_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='desk',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='desk',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='desks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='desk',
            unique_together={('name', 'user')},
        ),
    ]
