# Generated by Django 5.1.7 on 2025-03-28 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0004_deskgroup_deskusershare'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deskusershare',
            name='group',
        ),
        migrations.AddField(
            model_name='deskusershare',
            name='permission',
            field=models.CharField(choices=[('view', 'View Only'), ('admin', 'Admin'), ('owner', 'Owner')], default='view', max_length=10),
        ),
    ]
