# Generated by Django 5.1.7 on 2025-03-28 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0005_remove_deskusershare_group_deskusershare_permission'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DeskGroup',
        ),
    ]
