# Generated by Django 5.1.7 on 2025-03-25 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0005_alter_desk_name_alter_desk_user_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='desk',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='desk',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='desk',
            name='slug',
            field=models.SlugField(blank=True, max_length=100, unique=True),
        ),
    ]
